Import("env")

env.Append(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
    SDK_HEADERS=[
        File("one_wire_host.h"),
        File("one_wire_slave.h"),
        File("maxim_crc.h"),
    ],
    LINT_SOURCES=[
        Dir(".").srcnode(),
    ],
)

libenv = env.Clone(FW_LIB_NAME="one_wire")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
