Import("ENV")

kbd_env = ENV.Clone(
    tools=[
        "fwbin",
        "fbt_dist",
        ("compilation_db", {"COMPILATIONDB_COMSTR": "\tCDB\t${TARGET}"}),
    ],
)

kbd_env.Replace(
    FW_FLASH_TARGET_INTEFACE="target/stm32g0x.cfg",
    FIRMWARE_BUILD_CFG="keyboard",
    FW_FLASH_EXTRA_COMMANDS="reset_config srst_only srst_nogate connect_assert_srst",
)
kbd_env.AppendUnique(
    ASFLAGS=[
        "-mcpu=cortex-m0plus",
        "-g3",
        "-c",
        "-x",
        "assembler-with-cpp",
        "--specs=nano.specs",
        "-mfloat-abi=soft",
        "-mthumb",
    ],
    CPPDEFINES=[
        "DEBUG",
        "STM32G030xx",
        "USE_FULL_LL_DRIVER",
        ("HSE_VALUE", "8000000"),
        ("HSE_STARTUP_TIMEOUT", "100"),
        ("LSE_STARTUP_TIMEOUT", "5000"),
        ("LSE_VALUE", "32768"),
        ("EXTERNAL_CLOCK_VALUE", "12288000"),
        ("HSI_VALUE", "16000000"),
        ("LSI_VALUE", "32000"),
        ("VDD_VALUE", "3300"),
        ("PREFETCH_ENABLE", "1"),
        ("INSTRUCTION_CACHE_ENABLE", "1"),
        ("DATA_CACHE_ENABLE", "1"),
    ],
    CFLAGS=["-std=gnu11"],
    CCFLAGS=[
        "-mcpu=cortex-m0plus",
        "-g3",
        "-O0",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wall",
        "-Werror",
        "--specs=nano.specs",
        "-mfloat-abi=soft",
        "-mthumb",
    ],
    CPPPATH=[
        Dir("Core/Inc").srcnode(),
        Dir("Core/target").srcnode(),
        Dir("Drivers/STM32G0xx_HAL_Driver/Inc").srcnode(),
        Dir("Drivers/CMSIS/Device/ST/STM32G0xx/Include").srcnode(),
        Dir("Drivers/CMSIS/Include").srcnode(),
    ],
    LINKFLAGS=[
        "-mcpu=cortex-m0plus",
        "-T${LINKER_SCRIPT_PATH}",
        "--specs=nosys.specs",
        "-Wl,--gc-sections",
        "-static",
        "--specs=nano.specs",
        "-mfloat-abi=soft",
        "-mthumb",
        "-lc",
        "-lm",
        "-Wl,--no-warn-rwx-segment",
    ],
    LINKER_SCRIPT_PATH=File("STM32G030F6PX_FLASH.ld"),
)

fw_elf = kbd_env["FW_ELF"] = kbd_env.Program(
    target="keyboard",
    source=[
        File("Core/Startup/startup_stm32g030f6px.s"),
        kbd_env.GlobRecursive("*.c"),
    ],
)

fw_bin = kbd_env.BINBuilder("keyboard")

kbd_env.Alias("keyboard", fw_bin)

kbd_env.AddFwFlashTarget(kbd_env)

# kbd_cdb = kbd_env.CompilationDatabase()
# # without filtering, both updater & firmware commands would be generated in same file
# kbd_env.Replace(
#     COMPILATIONDB_PATH_FILTER=fwenv.subst("*${FW_FLAVOR}*"),
#     COMPILATIONDB_SRCPATH_FILTER="*.c*",
# )
# AlwaysBuild(fwcdb)
# Precious(fwcdb)
# NoClean(fwcdb)
# Alias(fwenv["FIRMWARE_BUILD_CFG"] + "_cdb", fwcdb)


# print("ENV:", ENV.Dump())
