from fbt.version import get_fast_git_version_id


Import("env")

env.Append(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
    LINT_SOURCES=[
        Dir(".").srcnode(),
    ],
    SDK_HEADERS=[
        File("api_lock.h"),
        File("compress.h"),
        File("manchester_decoder.h"),
        File("manchester_encoder.h"),
        File("path.h"),
        File("name_generator.h"),
        File("crc32_calc.h"),
        File("dir_walk.h"),
        File("args.h"),
        File("saved_struct.h"),
        File("float_tools.h"),
        File("value_index.h"),
        File("tar/tar_archive.h"),
        File("stream/stream.h"),
        File("stream/file_stream.h"),
        File("stream/string_stream.h"),
        File("stream/buffered_file_stream.h"),
        File("protocols/protocol_dict.h"),
        File("pretty_format.h"),
        File("hex.h"),
        File("simple_array.h"),
        File("bit_buffer.h"),
        File("keys_dict.h"),
        File("pulse_protocols/pulse_glue.h"),
        File("md5_calc.h"),
        File("varint.h"),
    ],
)


libenv = env.Clone(FW_LIB_NAME="toolbox")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
