Import("env")


env.Append(
    CPPPATH=[
        "#/",
        "#/lib",
        # Ugly hack
        Dir("../assets/compiled"),
    ],
)


libs = env.BuildModules(
    [
        "freertos"
    ],
)

Return("libs")
