Import("env")

env.Append(
    CPPPATH=[
        "#/",
        "#/lib",
        # Ugly hack
        Dir("../assets/compiled"),
    ],
)


libs = env.BuildModules(
    [
        "freertos",
        "mlib",
        "toolbox",
        "print",
        "fatfs",
        "nema_gfx",
        "tinyusb",
        "canvas",
    ],
)

Return("libs")
