Import("env")

env.Append(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
    SDK_HEADERS=[
        File("cc1101_regs.h"),
        File("st25r3916_reg.h"),
        File("st25r3916.h"),
    ],
    LINT_SOURCES=[
        Dir(".").srcnode(),
    ],
)


libenv = env.Clone(FW_LIB_NAME="hwdrivers")
libenv.ApplyLibFlags()

sources = Glob("*.c", source=True)

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
