#pragma once

typedef enum {
    /* Set 1*/
    FuriHalBusUSART1_PCLK,
    FuriHalBusUSART1_SCLK,
    FuriHalBusUSART2_PCLK,
    FuriHalBusUSART2_SCLK,
#ifdef SLI_SI917B0
    FuriHalBusQSPI_2_CLK,
    FuriHalBusQSPI_2_HCLK,
    FuriHalBusQSPI_2_M4_SOC_SYNC,
    FuriHalBusQSPI_2_CLK_ONEHOT,
#endif
    FuriHalBusCT_CLK,
    FuriHalBusCT_PCLK,
    FuriHalBusICACHE_CLK,
    FuriHalBusICACHE_CLK_2X,
    FuriHalBusRPDMA_HCLK,
    FuriHalBusSOC_PLL_SPI_CLK,
    FuriHalBusIID_CLK,
    FuriHalBusSDIO_SYS_HCLK,
    FuriHalBusCRC_CLK_M4,
    FuriHalBusM4SS_UM_CLK_STATIC_EN,
    FuriHalBusETH_HCLK,
    FuriHalBusHWRNG_PCLK,
    FuriHalBusGNSS_MEM_CLK,
    FuriHalBusCCI_PCLK,
    FuriHalBusCCI_HCLK,
    FuriHalBusCCI_CLK,
    FuriHalBusMASK_HOST_CLK_WAIT_FIX,
    FuriHalBusMASK31_HOST_CLK_CNT,
    FuriHalBusSD_MEM_INTF_CLK,
    FuriHalBusMASK_HOST_CLK_AVAILABLE_FIX,
    FuriHalBusULPSS_CLK,

    /* Set 2*/
    FuriHalBusGEN_SPI_MST1_HCLK,
    FuriHalBusCAN1_PCLK,
    FuriHalBusCAN1_CLK,
    FuriHalBusUDMA_HCLK,
    FuriHalBusI2C_BUS_CLK,
    FuriHalBusI2C_2_BUS_CLK,
    FuriHalBusSSI_SLV_PCLK,
    FuriHalBusSSI_SLV_SCLK,
    FuriHalBusQSPI_CLK,
    FuriHalBusQSPI_HCLK,
    FuriHalBusI2SM_SCLK,
    FuriHalBusI2SM_INTF_SCLK,
    FuriHalBusI2SM_PCLK,
    FuriHalBusQE_PCLK,
    FuriHalBusMCPWM_PCLK,
    FuriHalBusSGPIO_PCLK,
    FuriHalBusEGPIO_PCLK,
    FuriHalBusARM_CLK,
    FuriHalBusSSI_MST_PCLK,
    FuriHalBusSSI_MST_SCLK,
    FuriHalBusMEM2_CLK,
    FuriHalBusMEM_CLK_ULP,
    FuriHalBusROM_CLK,
    FuriHalBusPLL_INTF_CLK,
    FuriHalBusSEMAPHORE_CLK,
    FuriHalBusTOT_CLK,
    FuriHalBusRMII_SOFT_RESET,

    /* Set 3*/
    FuriHalBusBUS_CLK,
    FuriHalBusM4_CORE_CLK,
    FuriHalBusCM_BUS_CLK,
    FuriHalBusMISC_CONFIG_PCLK,
    FuriHalBusEFUSE_CLK,
    FuriHalBusICM_CLK,
    FuriHalBusMEM1_CLK,
    FuriHalBusMEM3_CLK,
    FuriHalBusUSB_PHY_CLK_IN,
    FuriHalBusQSPI_CLK_ONEHOT,
    FuriHalBusQSPI_M4_SOC_SYNC,
    FuriHalBusEGPIO_CLK,
    FuriHalBusI2C_CLK,
    FuriHalBusI2C_2_CLK,
    FuriHalBusEFUSE_PCLK,
    FuriHalBusSGPIO_CLK,
    FuriHalBusTASS_M4SS_64K_SWITCH_CLK,
    FuriHalBusTASS_M4SS_128K_SWITCH_CLK,
    FuriHalBusTASS_M4SS_SDIO_SWITCH_CLK,
    FuriHalBusTASS_M4SS_USB_SWITCH_CLK,
    FuriHalBusROM_MISC_STATIC,
    FuriHalBusM4_SOC_CLK_FOR_OTHER,
    FuriHalBusICACHE,

    /* ULP Section */
    FuriHalBusUlpTOUCH_SENSOR_PCLK,
    FuriHalBusUlpFIM_AHB_CLK,
    FuriHalBusUlpULPSS_TASS_QUASI_SYNC,
    FuriHalBusUlpULPSS_M4SS_SLV_SEL,
    FuriHalBusUlpAUX_SOC_EXT_TRIG_2_SEL,
    FuriHalBusUlpAUX_SOC_EXT_TRIG_1_SEL,
    FuriHalBusUlpAUX_ULP_EXT_TRIG_2_SEL,
    FuriHalBusUlpAUX_ULP_EXT_TRIG_1_SEL,
    FuriHalBusUlpTIMER_PCLK_EN,
    FuriHalBusUlpEGPIO_PCLK_EN,
    FuriHalBusUlpEGPIO_PCLK_DYN_CTRL_DISABLE_ULP,
    FuriHalBusUlpCLK_ULP_MEMORIES,
    FuriHalBusUlpVAD_CLK_EN,
    FuriHalBusUlpFIM_CLK_EN,
    FuriHalBusUlpREG_ACCESS_SPI_CLK_EN,
    FuriHalBusUlpEGPIO_CLK_EN,
    FuriHalBusUlpCLK_TIMER,
    FuriHalBusUlpVAD_PCLK,
    FuriHalBusUlpFIM_PCLK,
    FuriHalBusUlpSCLK_UART,
    FuriHalBusUlpPCLK_UART,
    FuriHalBusUlpSCLK_SSI_MASTER,
    FuriHalBusUlpPCLK_SSI_MASTER,
    FuriHalBusUlpCLK_I2S,
    FuriHalBusUlpPCLK_I2C,
    FuriHalBusUlpIR_PCLK_EN,
    FuriHalBusUlpPCM_FSYNC_START,
    FuriHalBusUlpPCM,
    /**/
    FuriHalBusMAX,
} FuriHalBus;
