Import("env")

from pathlib import Path

for dist_module in env.Glob("dist/*.scons"):
    # print("Dist module: ", dist_module)
    module_basename = Path(dist_module.name).stem
    env.RegisterComponent(f"dist_{module_basename}", dist_module.srcnode())

for fwenv_module in env.Glob("fwenv/*.scons"):
    # print("Fwenv module: ", fwenv_module, fwenv_module.abspath, type(fwenv_module))
    module_basename = Path(fwenv_module.name).stem
    env.RegisterComponent(f"fwenv_{module_basename}", fwenv_module.srcnode())

# aaaa
