Import("env")

env.Append(
    LINT_SOURCES=[Dir(".")],
)

env.Prepend(_LIBFLAGS="-Wl,--whole-archive ")
env.Append(_LIBFLAGS=" -Wl,--no-whole-archive")

libenv = env.Clone(FW_LIB_NAME="flipper${TARGET_HW}")
libenv.ApplyLibFlags()
libenv.Append(
    CCFLAGS=[
        "-Wno-unused-parameter",
        "-Wno-double-promotion",
        "-Wno-overflow",
    ],
)

lib = libenv.StaticLibrary(
    "${FW_LIB_NAME}",
    env.get("TARGET_CFG").gatherSources(),
)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
